apiVersion: v1
kind: Service
metadata:
  name: usconverters-uscdr301-base
  namespace: msp
  labels:
    app: usconverters-uscdr301-base
spec:
  selector:
    app: usconverters-uscdr301-base
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP