
apiVersion: v1
kind: Secret
metadata:
  name: registrar-registry-user-password
  namespace: default
type: Opaque
stringData:
  password: quinn
---
apiVersion: v1
kind: Secret
metadata:
  name: registrar-registry-erddap-author
  namespace: default
type: Opaque
stringData:
  author: registryadmin_password
