apiVersion: v1
kind: PersistentVolume
metadata:
  name: files-pv
  namespace: msp
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/msp/data/base"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
  namespace: envds
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi