apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-pv
  namespace: msp
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/envds/mqtt/base"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-pvc
  namespace: msp
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi