apiVersion: v1
kind: ConfigMap
metadata:
  name: synaccess-np05b-config
  namespace: msp
  labels:
    app: synaccess-np05b
data:
  interface.conf: |
    uid: syn100
    # serial_number: "1234"
    # daq_id: clearsky
    host: 192.168.1.100
    paths:
      port-1:
          # host: 192.168.1.100
          port: 23 # if omitted, default is used
