apiVersion: v1
kind: ConfigMap
metadata:
  name: netburner-sb70lc-nb52-config
  namespace: envds
  labels:
    app: netburner-sb70lc-nb52
data:
  interface.conf: |
    uid: nb52
    # serial_number: "1234"
    # daq_id: clearsky
    host: 10.55.169.52
    paths:
      port-1:
          # host: 10.55.169.52
          # host: 192.168.86.46 # can override interface host if needed?
          port: 23 # if omitted, default is used
      port-2:
          # host: 10.55.169.52
          # host: 192.168.86.46
          port: 24
      port-I2C:
          # host: 10.55.169.52
          # host: 192.168.86.46
          port: 26

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netburner-sb70lc-nb52
  namespace: envds
  labels:
    app: netburner-sb70lc-nb52
spec:
  selector:
    matchLabels:
      app: netburner-sb70lc-nb52
  template:
    metadata:
      labels:
        app: netburner-sb70lc-nb52
    spec:
      containers:
      - name: netburner-sb70lc-nb52
        image: envds-registry-clear:5000/envds/interface/netburner-sb70lc:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: clear
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: netburner-sb70lc-nb52-config
              mountPath: /app/config/interface.conf
              subPath: interface.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: netburner-sb70lc-nb52-config
          configMap:
            name: netburner-sb70lc-nb52-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: netburner-sb70lc-nb52
  namespace: envds
  labels:
    app: netburner-sb70lc-nb52
spec:
  selector:
    app: netburner-sb70lc-nb52
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: system-mock-uas1-stripprefix
#   namespace: envds
#   labels:
#     app: envds
# spec:
#   stripPrefix:
#     prefixes:
#       - /envds/interface/system/mock/01
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: system-mock-uas1-ingress
#   namespace: envds
#   # labels:
#   #   app: envds
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     traefik.ingress.kubernetes.io/router.middlewares:
#       envds-system-mock-uas1-stripprefix@kubernetescrd
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /envds/interface/system/mock/01
#         pathType: Prefix
#         backend:
#           service:
#             name: system-mock-uas1
#             port:
#               number: 9080

