apiVersion: v1
kind: ConfigMap
metadata:
  name: mockco-mock1-{serial_number}-config
  namespace: envds
  labels:
    app: mockco-mock1-{serial_number}
  # namespace: envds-cloudy
data:
  mock1.conf: |
    serial_number: "{serial_number}"
    interfaces:
      default: serial
      serial:
        interface: {serial-interface-instance-id}
        port: 02
      tcp:
      usb:
