apiVersion: v1
kind: ConfigMap
metadata:
  name: netburner-sb70lc-config
  namespace: msp
  labels:
    app: netburner-sb70lc
data:
  interface.conf: |
    uid: nb52
    # serial_number: "1234"
    # daq_id: clearsky
    host: 10.55.169.52
    paths:
      port-1:
          # host: 10.55.169.52
          # host: 192.168.86.46 # can override interface host if needed?
          port: 23 # if omitted, default is used
      port-2:
          # host: 10.55.169.52
          # host: 192.168.86.46
          port: 24
      port-I2C:
          # host: 10.55.169.52
          # host: 192.168.86.46
          port: 26
