name: Build Envds Package

on:
  push:
    branches: [ dev-* , add-envds-package-workflow']
    paths:
  
  pull_request:
    branches: [main, dev-*]
    paths:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        cd code/envds
        python -m pip install --upgrade pip setuptools wheel
        pip3 install 
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    
    - name: Run package creation
      run: |
        cd code/envds
        python -m pip3 install --user --upgrade build
        python -m build
    
    - name: Archive packages
      uses: actions/upload-artifact@v4
      with:
        name: envds
        path: code/envds/dist
