name: Build and Push synaccess-NP05B

on:

  push:
    branches: [ dev-*, controller-dashboard]
    paths:
      - 'code/apps/daq/controllers/Synaccess/NP05B/**'
  
  pull_request:
    branches: [main, dev-*, controller-dashboard]
    paths:
      - 'code/apps/daq/controllers/Synaccess/NP05B/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: synaccess-np05b
  # IMAGE_TAG: ${{ github.sha }}
  # IMAGE_TAG: $(cat VERSION)

jobs:

  build-and-push-synaccess-np05b:

    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: './code/apps/daq/controllers/Synaccess/NP05B'
      
    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    steps:

        - name: 'Checkout Main'
          uses: actions/checkout@v4

        - name: 'set env variables'
          run: |
            VER=$(cat VERSION)
            echo "IMAGE_TAG=$VER" >> $GITHUB_ENV
        # - name: Build the Docker image
        # #   run: docker build . --file Dockerfile --tag ghcr.io/acg/verifier:$(date +%s)
        #   run: docker build . --file Dockerfile --tag ghcr.io/acg/verifier:latest
    
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - name: 'Login to GitHub Container Registry'
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        # - name: Extract metadata (tags, labels) for Docker
        #   id: meta
        #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        #   with:
        #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        # - name: Build and push Docker image
        #   id: push
        #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        #   with:
        #     context: ./apps/verifier
        #     push: true
        #     tags: ${{ steps.meta.outputs.tags }}
        #     labels: ${{ steps.meta.outputs.labels }}
    
                
        # - name: Generate artifact attestation
        #   uses: actions/attest-build-provenance@v2
        #   with:
        #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        #     subject-digest: ${{ steps.push.outputs.digest }}
        #     push-to-registry: true

        - name: Build and push multi-platform image
          uses: docker/build-push-action@v4
          with:
            context: code/apps/daq/controllers/Synaccess/NP05B/.
            # dockerfile: code/apps/daq/sensors/AerosolDynamics/MAGIC250/Dockerfile
            push: true
            tags: |
              ghcr.io/noaa-pmel/msp/synaccess-np05b:${{env.IMAGE_TAG}}
            platforms: linux/amd64,linux/arm64

        # - name: Build the Docker image
        # #   run: docker build . --file Dockerfile --tag ghcr.io/acg/verifier:$(date +%s)
        #   run: docker build . --file Dockerfile --tag ghcr.io/noaa-pmel/msp/shelly-shellypro3:$IMAGE_TAG
 
        # - name: Push the Docker image
        #   run: docker push ghcr.io/noaa-pmel/msp/shelly-shellypro3:$IMAGE_TAG
