name: Build and Push kn-mqtt-adapter

on:

  push:

    branches: [ main, dev-system ]
      
    paths:

      - 'code/infrastructure/knative/eventing/adapter/kn-mqtt/**'
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kn-mqtt-adapter
  # IMAGE_TAG: ${{ github.sha }}
  # IMAGE_TAG: $(cat VERSION)

jobs:

  build-and-push-kn-mqtt-adapter:

    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: './code/infrastructure/knative/eventing/adapter/kn-mqtt'
      
    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    steps:

        - name: 'Checkout Main'
          uses: actions/checkout@v4

        - name: 'set env variables'
          run: |
            VER=$(cat VERSION)
            echo "IMAGE_TAG=$VER" >> $GITHUB_ENV
    
        - name: 'Login to GitHub Container Registry'
          uses: docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag ghcr.io/noaa-pmel/msp/kn-mqtt-adapter:$IMAGE_TAG
 
        - name: Push the Docker image
          run: docker push ghcr.io/noaa-pmel/msp/kn-mqtt-adapter:$IMAGE_TAG
